### ISSUE TITLE
Installation address problem

### ISSUE THREAD

**Issue by NightCrack** [patrickm32/proton-ge-custom-updater#8] opened 2021-01-01 20:17 UTC
Had to change an installation address in the script from <pre>$Home/.steam/root/compatibilitytools.d</pre> to <pre>/home/nightcrack/.steam/root/compatibilitytools.d</pre> to make installation work. Otherwise I've received <pre>mkdir: cannot create directory ‘/.steam/root/compatibilitytools.d’: No such file or directory
[Info] Created /.steam/root/compatibilitytools.d
tar: /.steam/root/compatibilitytools.d: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now</pre>

**Comment by p-mng** [comment] 2021-01-01 20:49
Seems like your `$HOME` environment variable is empty, usually it should point to `/home/<username>`. Would you mind sharing your distro/display manager/desktop environment? It would help to know whether this is an issue for all users or just your specific setup.

**Comment by NightCrack** [comment] 2021-01-02 06:49
I won't. How to (kinda newbie)?

**Comment by p-mng** [comment] 2021-01-02 10:10
The output of `cat /etc/*-release` should give the necessary info.

**Comment by NightCrack** [comment] 2021-01-03 22:47
os-release
<pre>NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal</pre>
lsb-release
<pre>DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"</pre>

**Comment by p-mng** [comment] 2021-01-14 21:44
Unfortunately, I cannot reproduce the issue. I also tested in a clean Ubuntu 20.04 VM and by manually emptying the `HOME` environment variable, however the script still exits with a clean error.

Perhaps some other software is interfering here or it is due to other setup specific things, but I will close the issue for now. If someone else has the error I will reopen it take a closer look.

**Closed as completed by p-mng** 2021-01-14 21:44 UTC
